spring.application.name=TaskManagerESBot
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=123
spring.docker.compose.enabled=false
bot.token=7833338301:AAFvVeia58EHBjtkQuhyO9Av15F13uNasqo

